--LISTANDO AS BASES DE DADOS--
SHOW DATABASES;

--DELETANDO UMA BASE DE DADOS--
DROP DATABASE teste;

--CRIANDO UMA BASE DE DADOS--
CREATE DATABASE teste;

--VERIFICAR AVISOS--
SHOW WARNINGS;

--MELHORANDO A SEMANTICA CRIAÇÃO DE BASE DE DADOS--
CREATE DATABASE IF NOT EXISTS teste;

--MELHORANDO A SEMANTICA PARA DELETAR UMA BASE
DROP DATABASE IF EXISTS testes;

--VAMOS DEIXAR A BASE DE DADOS TESTE CRIADA--
CREATE DATABASE IF NOT EXISTS teste;