--ENTRANDO EM UMA BASE DE DADOS--
USE teste;

--CRIANDO UMA TABELA--

CREATE TABLE customers(
    id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--LISTANDO AS TABELAS--
SHOW TABLES;
--DESCREVENDO OS ATRIBUTOS DE UMA TABELA--
DESCRIBE customers;
--ou--
SHOW COLUMNS FROM customers;

--CRIANDO A TABELA ORDERS--
CREATE TABLE IF NOT EXISTS orders(
    id INT AUTO_INCREMENT PRIMARY KEY,
    amount NUMERIC(7,2),
    customer_id INT,
    FOREIGN KEY (customer_id) REFERENCES customers(id)
);
DESCRIBE orders;